"""Render the daily Markdown digest into an email-friendly HTML body."""
from __future__ import annotations

import markdown as md

CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 720px; margin: 0 auto; padding: 24px; color: #1a1a1a; line-height: 1.55; }
h1 { border-bottom: 2px solid #333; padding-bottom: 8px; }
h2 { margin-top: 32px; color: #2c5282; }
ul { padding-left: 20px; }
li { margin-bottom: 12px; }
a { color: #2b6cb0; text-decoration: none; }
a:hover { text-decoration: underline; }
strong { color: #1a202c; }
.footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd;
          font-size: 12px; color: #888; }
"""


def to_html(markdown_text: str, repo_url: str = "") -> str:
    body_html = md.markdown(markdown_text, extensions=["extra", "sane_lists"])
    footer = (f'<div class="footer">Auto-generated by '
              f'<a href="{repo_url}">daily-digest</a>. '
              f'Built with Claude API.</div>') if repo_url else ""
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><style>{CSS}</style></head>
<body>{body_html}{footer}</body></html>"""
